Rails.application.routes.draw do
  # get 'home/index'
  root 'home#index'

  devise_for :users #auto generated by devise
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources :conversations, only: [:create] #this gives the same thing as below, but this is more automated and less error-prone
  # post 'conversations', to: 'conversations#create'
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end


end
